### ISSUE TITLE
Bug: Block overlay renderer ignores camera tilt

### ISSUE THREAD

**Issue by m0oncatcher** [Tektonikal/CustomBlockHighlight#1]
![2024-04-07_18 59 13](https://github.com/Tektonikal/CustomBlockHighlight/assets/87122608/e8a99a1a-1b77-43f9-b364-af9a8475d5ae)

Once the camera is tilted by using a mod like [do a barrel roll](https://modrinth.com/mod/do-a-barrel-roll), the outlines become misaligned.

**Comment by Tektonikal** [comment]
Got this fixed, will no longer be an issue with future updates
I was doing some dumb matrix magic that caused it
