### ISSUE TITLE
Update dependency to support 1.21.1

### ISSUE THREAD

**Issue by RoonMoonlight** [Tektonikal/CustomBlockHighlight#3]
So Mojang recently announced [Minecraft 1.21.1](https://www.minecraft.net/en-us/article/minecraft-java-edition-1-21-1), which contains small hotfix. It requires the mod to be updated as it asks for 1.21 instead of 1.21.1. Thank you as always

**Comment by Tektonikal** [comment]
I've hopefully cleared my schedule for the weekend, so I'll be able to make enough progress on updating / porting my mods by then. This mod is a priority, only a few minor features / changes left to make.

**Comment by Tektonikal** [comment]
All done, should work fine and be available on CF and Modrinth
Decided to do this before the update because it might take a little bit longer, and IntelliJ has been needing a bit more wrangling than usual.
