### ISSUE TITLE
Incompatible with 1.21.2/1.21.3 Update

### ISSUE THREAD

**Issue by RoonMoonlight** [Tektonikal/CustomBlockHighlight#5]
Howdy, I tested this mod with 1.21.2 and 1.21.3 with dependency overrides, but the game crashes on launch. Seems Mojang made changes to the feature that led to breakage. Would be cool if this can be updated for 1.21.2 and 1.21.3 release.

Crash report:
https://mclo.gs/smeQvgT

**Comment by Tektonikal** [comment]
fixed the inject target, should work normally now. Stay tuned for a big update soon.

**Comment by Tektonikal** [comment]
Will publish on modrinth and curseforge in a minute.
