### ISSUE TITLE
Overlay becomes offset at distances far from 0 0

### ISSUE THREAD

**Issue by Kladki** [Tektonikal/CustomBlockHighlight#6]
The block overlay drifts away from the actual position of the block the future you go from the centre of the world.

To reproduce, teleport 5 million blocks in x and y from spawn. Smaller distances will still have drift, but it becomes very clear at this distance.
![image](https://github.com/user-attachments/assets/23044e48-b794-412e-a374-101b0539b289)

**Comment by Tektonikal** [comment]
already reported, will be fixed with next release

**Comment by Tektonikal** [comment]
Fixed for 1.21.2+, will publish the fixed version along with the next update.
